### PR TITLE
View Schedule

### PR DESCRIPTION
**Pull request by allenyong926**
yesterday we done discuss the create schedule function....today lets start discuss the view schedule function in schedule module. Any idea ??

### CODE REVIEW

**Comment by sh9312** [comment]
get those important field first 
eg.bus number, date, time etc

**Comment by allenyong926** [comment]
ok senghong....that detail must have

**Comment by allenyong926** [comment]
got another suggestion ??

**Comment by CheowChenWei** [comment]
maybe have schedule  id? for each schedule. and location display form starting point and the destination

**Comment by sh9312** [comment]
set it as primary key then 
make things easy to retrieve

**Comment by allenyong926** [comment]
chenwei i think use bus No better

**Comment by CheowChenWei** [comment]
OH~ i see then the location is ok right?

**Comment by tmwong95** [comment]
i agree yang....if use schedule id will make the database no clearly, because we have the bus no alrdy

**Comment by allenyong926** [comment]
sure chenwei the location must have

**Comment by tmwong95** [comment]
senghong that is a good point, set primary key can let the database become better

**Comment by allenyong926** [comment]
how about the design ?? need use wht to display it ??

**Comment by tmwong95** [comment]
i think use table to display it....can make the details clearly and let customer ez to see

**Comment by sh9312** [comment]
good suggestion tm
it will make it look neat and tidy

**Comment by allenyong926** [comment]
yes i also agree it

**Comment by allenyong926** [comment]
any idea wan add it??... if no lets start do the view schedule module :smile:

**Comment by sh9312** [comment]
nope
what about you two, tm and chen wei ?

**Comment by tmwong95** [comment]
nope let start do it

**Comment by CheowChenWei** [comment]
just start it ~

**Pull request merged**
