### PR TITLE
Update function for the schedule

### PR DESCRIPTION
**Pull request by tmwong95**
guys, lest add the update function for the schedule model

### CODE REVIEW

**Comment by allenyong926** [comment]
hi

**Comment by tmwong95** [comment]
my idea is let the user can change the schedule details similar the create schedule function

**Comment by allenyong926** [comment]
ok tm, we also can add the search function button to ensure the details is user want to change it

**Comment by tmwong95** [comment]
yes this is a good function for the user ....i agree it . chenwei and senghong any suggestion ??

**Comment by CheowChenWei** [comment]
also can add the reset button so that can clear all data after having wrong enter.

**Comment by allenyong926** [comment]
yup chenwei that function is convenience for the user

**Comment by allenyong926** [comment]
i agree it

**Comment by tmwong95** [comment]
yes chenwei i aslo agree u point

**Comment by tmwong95** [comment]
ok today we discuss until here 1st let do the requirement we list out

**Comment by allenyong926** [comment]
ok

**Pull request merged**
