### PR TITLE
Payment Module

### PR DESCRIPTION
**Pull request by allenyong926**
last week we done the schedule module alrdy...today lets start the payment module... .any idea guys ??

### CODE REVIEW

**Comment by allenyong926** [comment]
i got idea how about confirm purchase ticket, the system will auto jump to the payment page and calculate the total amount ?

**Comment by tmwong95** [comment]
yes i agree it ...and how we let the user can view schedule before thy need to purchase ticket ??

**Comment by sh9312** [comment]
well, we could try auto retrieve it directly from database

**Comment by allenyong926** [comment]
sure tm , can let user ensure the schedule information thy choose correct...this is a good point

**Comment by allenyong926** [comment]
erm...senghong u mean is retrieve wht data ??

**Comment by sh9312** [comment]
the schedule from database

**Comment by allenyong926** [comment]
ok senghong ....sure i agree it

**Comment by tmwong95** [comment]
ya....i got another idea, how we also add the reset button for this module same like another 2 module ?? so when user enter wrong ,can just click the button reset it and enter again.

**Comment by CheowChenWei** [comment]
ya this is not bad  easy for user erase data

**Comment by allenyong926** [comment]
yes it is a useful button . how about u chenwei ??

**Comment by CheowChenWei** [comment]
before customer purchase ticket can let user enter customer details.

**Comment by sh9312** [comment]
sounds good, chen wei

**Comment by allenyong926** [comment]
haha senghong

**Comment by CheowChenWei** [comment]
what mean sound good?

**Comment by sh9312** [comment]
it means good idea

**Comment by CheowChenWei** [comment]
i see thank you ：）

**Comment by tmwong95** [comment]
hahaha ....chenwei that is a good idea ...can record the ticket for who customer

**Comment by sh9312** [comment]
we need a save function too

**Comment by allenyong926** [comment]
save function?? u mean save the payment details ?

**Comment by tmwong95** [comment]
yes ....yang i think senghong mean use for save the details to database

**Comment by sh9312** [comment]
yea, we need one don't you think ?

**Comment by CheowChenWei** [comment]
and we need to print receipt return to customer also

**Comment by allenyong926** [comment]
yes i think we need it ....payment record is very important

**Comment by CheowChenWei** [comment]
maybe we can all print button

**Comment by tmwong95** [comment]
chenwei wht mean all print button ??

**Comment by sh9312** [comment]
like how all print button?

**Comment by allenyong926** [comment]
ya wht mean it lol

**Comment by CheowChenWei** [comment]
haha type wrongly XD  is add

**Comment by allenyong926** [comment]
lol chenwei haha..but we need this fucntion also need to print the receipt to the customer

**Comment by tmwong95** [comment]
ya chenwei type wrong lol...but it is important function

**Comment by allenyong926** [comment]
so anyone got any more idea ?? if not we will start this module

**Comment by tmwong95** [comment]
no

**Comment by sh9312** [comment]
nope

**Comment by allenyong926** [comment]
ok lets start do this module

**Comment by allenyong926** [comment]
guys how u part ?? it is ok or have face any problem ?

**Comment by tmwong95** [comment]
i still doing the view schedule and the reset button mayb tomorrow can finish it

**Comment by allenyong926** [comment]
ok tm

**Comment by allenyong926** [comment]
i also need some time doing the calculation part but done abit alrdy

**Comment by CheowChenWei** [comment]
i have done create all text field for user fill in customer detail already

**Comment by allenyong926** [comment]
well done chenwei

**Comment by tmwong95** [comment]
yang i done my part alrdy how about u ?

**Comment by allenyong926** [comment]
i also want done alrdy...mayb tonight will finish

**Comment by tmwong95** [comment]
ok now i doing another 2 part with senghong and chenwei also will done later

**Comment by allenyong926** [comment]
ok

**Comment by sh9312** [comment]
i and tat minn done the view schedule 
and the save button too

**Comment by tmwong95** [comment]
yes and chenwei also done the print function with me

**Comment by CheowChenWei** [comment]
Ya, im done the print function

**Comment by allenyong926** [comment]
chenwei our calculation part  not done yet

**Comment by allenyong926** [comment]
The calculation part will delay ...mayb tomorrow done because today i use the time to solve the calendar problem

**Comment by CheowChenWei** [comment]
i go do the printing function no time to do the calculation part

**Comment by tmwong95** [comment]
its ok, we now just left the calculation only so wait u 2 done the part thn we can complete this module

**Comment by allenyong926** [comment]
ok tm tomorrow me and chenwei will done it

**Comment by allenyong926** [comment]
the calculation part me and chenwei done alrdy

**Comment by CheowChenWei** [comment]
same here done the calculation

**Comment by tmwong95** [comment]
good job

**Pull request merged**
