### PR TITLE
Display or retrieve staff

### PR DESCRIPTION
**Pull request by tmwong95**
How do u all think about it?

### CODE REVIEW

**Comment by CheowChenWei** [comment]
maybe we can create one table to display all staff detail.  Grid View XD

**Comment by sh9312** [comment]
search the staff details via staff ID

**Comment by sh9312** [comment]
the DB will look for the primary key 
and retrieve it

**Comment by CheowChenWei** [comment]
that table we display some infor let user view such as staff ID, Name, and IC etc and if want see more detail then search by staff id to retrieve staff infor

**Comment by allenyong926** [comment]
chenwei i agree display all staff detail but maybe we don't use the grid view to display

**Comment by tmwong95** [comment]
yes seng hong i agree use id , it will make user easily to search the staff detail

**Comment by allenyong926** [comment]
chenwei i also think don't use the grid view display staff details

**Comment by tmwong95** [comment]
yes i agree yang, don't use the grid view display staff details

**Pull request merged**
