### PR TITLE
Schedule Model

### PR DESCRIPTION
**Pull request by allenyong926**
all i want design a schedule module for our bus ticketing system.....1st we do the create function, got any idea suggest ??

### CODE REVIEW

**Comment by tmwong95** [comment]
schedule is used for bus...so when we create a new schedule can let the user select the bus no

**Comment by tmwong95** [comment]
ok tm. gd point

**Comment by allenyong926** [comment]
good idea tm....can let user assign the schedule to the bus based on bus no

**Comment by CheowChenWei** [comment]
beside that, also can create few text field to collect customer date and time

**Comment by CheowChenWei** [comment]
beside that, also can create few text field to let user choose the date

**Comment by allenyong926** [comment]
good point chenwei, i will add in to the create schedule module

**Comment by tmwong95** [comment]
we also can let user select the bus from where location go to where location

**Comment by allenyong926** [comment]
i agree tm...this function also important for the schedule

**Comment by CheowChenWei** [comment]
And the price, also need let the user set the price for the each schedule.

**Comment by tmwong95** [comment]
that is good idea chenwei

**Comment by allenyong926** [comment]
yes chen wei, i also thinking same idea

**Comment by allenyong926** [comment]
how about i display the seat of the bus form the bus database in the create schedule module because when user create a new schedule, user and customer can know the schedule available how many seat ??

**Comment by CheowChenWei** [comment]
Yes! This is useful part for schedule. I agree it.

**Comment by tmwong95** [comment]
yes i also agree it

**Comment by allenyong926** [comment]
ok we discuss until here good job everyone

**Pull request merged**
