### PR TITLE
Delete Schedule

### PR DESCRIPTION
**Pull request by allenyong926**
guys, this is last function we add in schedule module....any idea ?

### CODE REVIEW

**Comment by tmwong95** [comment]
i think we can same like the update schedule function....add the search button because can let user ensure the information is user confirm want to delete

**Comment by sh9312** [comment]
if we want to delete, let's start by getting the bus number as reference

**Comment by allenyong926** [comment]
good idea tm....it is a useful button to user

**Comment by allenyong926** [comment]
senghong mean that we use the bus number to get the schedule information 1st thn delete it ??

**Comment by sh9312** [comment]
yes, search first then only confirm delete

**Comment by allenyong926** [comment]
ok i agree but how we get the bus number ?? we set it or ??

**Comment by sh9312** [comment]
hmmm....directly auto fetch from the database ?

**Comment by CheowChenWei** [comment]
just retrieve it with that schedule record i think

**Comment by tmwong95** [comment]
yes just retrieve the bus number in the database

**Comment by allenyong926** [comment]
ok any idea ??

**Comment by CheowChenWei** [comment]
cancel button?

**Comment by CheowChenWei** [comment]
clear all data from text field that is user retrieve one

**Comment by allenyong926** [comment]
erm..mean when the user select the bus number to get the schedule information is not user want...user can clear all information and select again ??

**Comment by sh9312** [comment]
yes exactly

**Comment by CheowChenWei** [comment]
yes that is what i mean

**Comment by sh9312** [comment]
what's next then ?

**Comment by allenyong926** [comment]
nice.... good suggestion for the delete function, senghong i think enough because i wan the delete function is simply xD

**Comment by sh9312** [comment]
oh ok, let's start working on it then

**Comment by tmwong95** [comment]
yes lest start it

**Pull request closed without merging**
