### PR TITLE
Create Staff

### PR DESCRIPTION
**Pull request by tmwong95**
Lets talk About Create Staff Module? What attribute we need to apply?

### CODE REVIEW

**Comment by sh9312** [comment]
testing comment, can see me ?

**Comment by tmwong95** [comment]
yes, seng hong

**Comment by allenyong926** [comment]
i think can let the user select the position

**Comment by sh9312** [comment]
start with staff's ID 
let's make it auto generate

**Comment by tmwong95** [comment]
Allenyong, yes i agree with u! some work can only be done by manager , and normal staff can only access to those normal function

**Comment by sh9312** [comment]
maybe only manager can create staff ?

**Comment by allenyong926** [comment]
Another i suggest where create a staff need to select the security question and answer because can used by recovery they password

**Comment by allenyong926** [comment]
yes. seng hong i agree , we need let the system have different function based on position

**Comment by allenyong926** [comment]
anyone have any suggestion ?

**Comment by sh9312** [comment]
for the address, let's separate it into different input 
instead inside one big textbox

**Comment by sh9312** [comment]
we'll have street address textbox , zip code textbox, city textbox and etc

**Comment by tmwong95** [comment]
how about contact number?

**Comment by allenyong926** [comment]
yes seng hong ,we need do that because if write in one textbox will make the address not clear

**Comment by allenyong926** [comment]
tmwong i think the contact number must have because it is the way let user contact to they staff

**Comment by CheowChenWei** [comment]
another attribute, can recommend staff give their email.

**Comment by tmwong95** [comment]
okay allenyong!

**Comment by CheowChenWei** [comment]
so that we can send any promotion or recover password through email.

**Comment by tmwong95** [comment]
chenwei! i very agree to u...

**Comment by allenyong926** [comment]
yes chen wei. we aslo can provide the validation for the email so that can keep the format for the email.

**Comment by tmwong95** [comment]
Lastly..... Contact number is important also

**Pull request merged**
