### PR TITLE
Update staff details

### PR DESCRIPTION
**Pull request by tmwong95**
how do u all think about update part?

### CODE REVIEW

**Comment by tmwong95** [comment]
hi my fren , i suggest a part call update .. do u all agree?

**Comment by allenyong926** [comment]
i agree . the system should have update function for user update they information. How about we use name for the update function

**Comment by CheowChenWei** [comment]
er... how about just use ID to update, because many ppl may have same name is difficult to find out which is belong to this user.

**Comment by allenyong926** [comment]
yes ...chenwei u point is better

**Comment by sh9312** [comment]
good point, some people may have the same name 
we don't want to update the wrong person

**Comment by tmwong95** [comment]
how about we add the read function ?? because can let the user see the old one information

**Comment by allenyong926** [comment]
i agree u tm .....because can let user confirm the information they update

**Comment by CheowChenWei** [comment]
Yes! i agree

**Pull request merged**
