### PR TITLE
delete staff

### PR DESCRIPTION
**Pull request by allenyong926**
last function we discuss is delete staff function....any idea ??

### CODE REVIEW

**Comment by sh9312** [comment]
we search the staff we want to delete first

**Comment by allenyong926** [comment]
i agree senghong....we use the staff id to delete staff because if use name will have same problem with update

**Comment by tmwong95** [comment]
yes yang. I agree u point if we use name will accidentally deleted the same name of the staff information

**Comment by CheowChenWei** [comment]
We also can allow system prompt out error message when the id is not have in database.

**Comment by allenyong926** [comment]
Sure chenwei that is a good point

**Comment by tmwong95** [comment]
Wow… fastastic

**Pull request merged**
